### ISSUE TITLE
down arrows to have more contrast

### ISSUE THREAD

**Issue by rjpartingtoniii** [JustinHolmesMusic/justinholmes.com#132]
<img width="1410" alt="Screen Shot 2023-09-01 at 5 53 51 PM" src="https://github.com/JustinHolmesMusic/VowelSoundsAlbumDrop/assets/78699050/80c2ddc2-fe92-47a1-a1c2-beac0723f4cf">

**Comment by jMyles** [comment]
This is done a while ago.
