### ISSUE TITLE
Wrongly placed JM studio photos

### ISSUE THREAD

**Issue by kubic71** [JustinHolmesMusic/justinholmes.com#23]
One image has wrong path and doesn't load, the other one is too small:

![image](https://github.com/jMyles/VowelSoundsAlbumDrop/assets/12272640/31af74e0-8260-47b0-9573-a643275065ce)

And the rest is on the bottom of the page - maybe they are too small to be visible?
![image](https://github.com/jMyles/VowelSoundsAlbumDrop/assets/12272640/33bfd3c1-6599-4748-a8a9-7e79286edcbf)

**Comment by kubic71** [comment]
Should  be fixed by https://github.com/jMyles/VowelSoundsAlbumDrop/pull/20
Let's merge that then @jMyles @KPrasch 


![image](https://github.com/jMyles/VowelSoundsAlbumDrop/assets/12272640/8c9fc4c2-a11f-41f2-ac4a-5fed00a708fe)


![image](https://github.com/jMyles/VowelSoundsAlbumDrop/assets/12272640/678b5b2e-3488-418c-97c0-d86a8b71d276)

**Comment by KPrasch** [comment]
I'd like to take an attempt at improving this PR before merging 🙏🏻

**Comment by kubic71** [comment]
@jMyles can we close this?
